paths:
  /api/products:
    get:
      summary: Devuelve los productos creados
      tags:
        - Products
      responses:
        "200":
          description: Los productos se obtienen correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, en este endpoint se debera a un error en la base de datos
    post:
      summary: crea un producto nuevo
      tags:
        - Products
  /api/products/{pid}:
    get:
      summary: devuelve el producto con dicho id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto
        schema:
          type: string
      responses:
        "200":
          description: el producto se obtienen correctamente
        "404":
          description: Producto no encontrado
    put:
      summary: actualiza los datos el producto con dicho id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/UpdateProduct'
      responses:
        "200":
          description: el producto se actualizo correctamente
        "403":
          description: sin autorizacion
        "404":
          description: Producto no encontrado
    delete:
      summary: elimina el producto con dicho id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto
        schema:
          type: string
      responses:
        "200":
          description: el producto se borro correctamente
        "403":
          description: sin autorizacion
        "404":
          description: Producto no encontrado 

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: id unico del producto
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripción del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
        thumbnail:
          type: string
          description: url de la imagen del producto
        code:
          type: string
          description: codigo del producto
        owner:
          type: string
          description: propietario de producto
        status:
          type: boolean
          description: estatus del producto
  requestBodies:
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripción del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
        thumbnail:
          type: string
          description: url de la imagen del producto
        code:
          type: string
          description: codigo del producto
        status:
          type: boolean
          description: estatus del producto
